# Generated by Django 5.0 on 2024-02-21 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genre', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='books/images/')),
                ('author', models.CharField(max_length=255)),
                ('synopsis', models.TextField(max_length=1000)),
                ('editorial', models.CharField(max_length=255)),
                ('dayPublication', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pages', models.IntegerField(max_length=10)),
                ('formats', models.CharField(max_length=255)),
                ('isbn', models.IntegerField(max_length=15)),
                ('document', models.URLField()),
                ('language', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statusk', models.CharField(max_length=20)),
                ('published', models.BooleanField(default=False)),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='genre.genre')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
